#Este yaml monitorea el directorio donde estan los manifiestos que crean los proyectos en argocd
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-project
  namespace: argocd
spec:  
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: argocd
  source:
    repoURL: https://github.com/fmoreno0207/Autometion-project.git
    path: argocd-self-manage/argocd-project
    directory:
      recurse: true
      jsonnet: {}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
