#Este yaml monitorea el directorio donde estan los manifiestos que crean los proyectos en argocd
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: argocd
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/fmoreno0207/Autometion-project.git
    path: argocd-self-manage/argocd-project
    helm:
      valueFiles:
        - values-custom.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
