apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aargocd-application-of-apps
  namespace: argocd
spec:
  project: argocd
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/fmoreno0207/Autometion-project.git
    path: helm
    helm:
      valueFiles:
        - values-custom.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
