apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx
  namespace: argocd
spec:
  project: awx
  destination:
    namespace: awx
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/fmoreno0207/Autometion-project.git
    path: helm/awx
    helm:
      valueFiles:
        - values-custom.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
