apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-app
  namespace: argocd
spec:  
  destination:
    namespace: simple-app
    server: https://kubernetes.default.svc
  project: simple-app
  source:
    repoURL: https://github.com/fmoreno0207/Autometion-project.git
    path: argocd-self-manage/argocd-application
    directory:
      recurse: true
      jsonnet: {}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
